version: '3.7'

services:
  web:
    restart: always
    build: ./src
    container_name: backend_deploy_aws
    command: ["/entrypoint.sh"]
    env_file:
      - ./src/.env
    volumes:
      - ./src:/usr/src/app
      - static_volume:/usr/src/app/staticfiles
    networks:
      - deploy_aws_network
    depends_on:
      - db

  db:
    image: 'postgres:latest'
    container_name: postgres_deploy_aws
    env_file:
      - ./src/.env
    ports:
      - "5433:5432"
    volumes:
      - ./src/init.sql:/docker-entrypoint-initdb.d/init.sql
      - deploy_aws_data:/var/lib/postgresql/data/
    networks:
      - deploy_aws_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: deploy_aws_pgadmin
    ports:
      - "3333:80"
    env_file:
      - ./src/.env
    links:
      - db:db
    depends_on:
      - db
    volumes:
      - mate_pgadmin_data:/var/lib/pgadmin
    networks:
      - deploy_aws_network

  nginx:
    build:
      context: ./nginx
    container_name: nginx_service
    ports:
      - "80:8000"
    depends_on:
      - web
    volumes:
      - static_volume:/usr/share/nginx/html/static
    networks:
      - deploy_aws_network

networks:
  deploy_aws_network:
    driver: bridge

volumes:
  deploy_aws_data:
    driver: local
  mate_pgadmin_data:
    driver: local
  static_volume:
    driver: local


